const QUEUES = {
  USER_REGISTERED: "AUTH_NOTIFICATION_USER_CREATED",
  USER_LOGIN: "AUTH_NOTIFICATION_USER_LOGIN",
  PAYMENT_SUCCESS: "PAYMENT_NOTIFICATION_SUCCESSFUL",
  PAYMENT_FAILED: "PAYMENT_NOTIFICATION_FAILED",
  ORDER_CANCELLED : "ORDER_CANCELLED",
  PRODUCT_NOTIFICATION_PRODUCT_CREATED: "PRODUCT_NOTIFICATION_PRODUCT_CREATED"

}
module.exports = QUEUES