const QUEUES = {
  PAYMENT_INITIATED: "PAYMENT_NOTIFICATION.PAYMENT_INITIATED",
  PAYMENT_SUCCESS: "PAYMENT_NOTIFICATION.PAYMENT_COMPLETED",
  PAYMENT_FAILED: "PAYMENT_NOTIFICATION.PAYMENT_FAILED",
}
module.exports = QUEUES