const QUEUES = {
  USER_REGISTERED: "AUTH_NOTIFICATION_USER_CREATED",
  USER_LOGIN: "AUTH_NOTIFICATION_USER_LOGIN",
  PAYMENT_SUCCESS: "PAYMENT_NOTIFICATION_SUCCESSFUL",
  PAYMENT_FAILED: "PAYMENT_NOTIFICATION_FAILED",
  SELLER_AUTH_REGISTER : "AUTH_SELLER_DASHBOARD_USER_CREATED",
  SELLER_DASHBOARD_PRODUCT_CREATED :"PRODUCT_SELLER_DASHBOARD_PRODUCT_CREATED",
PRODUCT_NOTIFICATION_PRODUCT_CREATED: "PRODUCT_NOTIFICATION_PRODUCT_CREATED"
}
module.exports = QUEUES